# Apps configuration for MPIS
#
# Usage:
#
# section: Title
#   option: Title
#     exec: sys_upgrade
#       install:
#         - "package1"
#         - "package2"
#       command: ["command1", "command2"]
#     kde: true # (if package is for KDE, if current DE/WM is not KDE print a warning, BTW I need to implement it :P)
#     aur: true # (if package comes from AUR, I will probably use this later)
#

# NOTES:
#   - Package management commands will make use of `yaourt` only (trying to avoid duplicity)
#   - Differences between apps.config and this file will be listed as comments

# TODO:
#   - Add a description between sections (like AUI for Arch does)
#   - Search for TODO in this document


# System update and more stuff
system_update: System update

  keys: Refresh mirrors and keys
    exec:
      command: ["yaourt -S archlinux-keyring manjaro-keyring", "sudo pacman-keys --init", "sudo pacman-keys --populate archlinux manjaro", "sudo pacman-mirrors -g"]

  upgrade: System upgrade
    exec: sys_upgrade

  cache: Clean package cache
    exec:
      command: ["yaourt -Scc"]

  orphans: Remove orphans
    exec:
      command: ["yaourt -Rsn"]


# Office section (OpenOffice is depreciated)
office_suites: Office

  libreoffice_still: LibreOffice Still (more stable)
    exec:
      install:
        - libreoffice-still # TODO: Set the GTK+ 2 UI render for LibreOffice because GTK+ 3's is buggy, implement a language installer

  libreoffice_fresh: LibreOffice Fresh (more updated)
    exec:
      install:
        - libreoffice-fresh

  calligra: Calligra Suite
    exec:
    kde: true
      install:
        - calligra

  wps: WPS Office
    aur: true
    exec:
      command: ["yaourt -G wps-office", "cd wps-office", "yaourt -G libpng12", "cd libpng12", "makepkg -sic", "cd ..", "makepkg -sic", "cd ..", "rm -rf "wps-office"] # TODO: Make this less horrible!


multimedia_players: Multimedia (Players) # TODO: Add more and divide betwheen Audio and Video

  audacious: Audacious
    exec:
      install:
        - audacious

  moc: MOC (Music On Terminal)
    exec:
      install:
        - moc

  vlc: VLC
    exec:
      install:
        - vlc

  smplayer: SMPlayer
    exec:
      install:
        - smplayer # Put those guys...

  smtube: SMTube
    exec:
      install:
        - smtube # ... together (same author)

  mpv: MPV
    exec:
      install:
        - mpv

  totem: GNOME Videos (Totem)
    exec:
      install:
        - totem


multimedia_recorders: Multimedia (Recorders)

  ssr: Simple Screen Recorder
    exec:
      install:
        - simplescreenrecorder

  vokoscreen: VokoScreen
    exec:
      install:
        - vokoscreen

  obs_studio: Open Broadcasting Studio
    exec:
      install:
        - obs-studio


multimedia_editors: Multimedia (Editors)

  openshot: OpenShot
    exec:
      install:
        - openshot

  kdenlive: KDEnlive
    kde: true
    exec:
      install:
        - kdenlive

  audacity: Audacity
    exec:
      install:
        - audacity


multimedia_converters: Multimedia (Converters)

  handbrake: Handbrake
    exec:
      install:
        - handbrake

  soundconverter: SoundConverter (GTK)
    exec:
      install:
        - soundconverter

  soundkonverter: SoundKonverter (Qt)
    exec:
      install:
        - soundkonverter


multimedia_burners: Multimedia (Burners)

  sound_juicer: Sound Juicer
    exec:
      install:
        - sound-juicer

  brasero: Brasero
    exec:
      install:
        - brasero

  k3b: K3B
    kde: true
    exec:
      install:
        - k3b # TODO: Add optional dependencies to make it work


multimedia_downloaders: Multimedia (Downloaders)

  clipgrab: ClipGrab
    exec:
      install:
        - clipgrab

  youtube_dl: Youtube-DL
    exec:
      install:
        - youtube-dl


multimedia_centers: Multimedia (Centers)

  kodi: Kodi
    exec:
      install:
        - kodi


development_editors: Development (Editors)

  geany: Geany
    exec:
      install:
        - geany

  sublime_text_2: Sublime Text 2
    aur: true
    exec:
      install:
        - sublime-text

  sublime_text_3: Sublime Text 3
    aur: true
    exec:
      install:
        - sublime-text-dev

  eclipse: Eclipse
    exec:
      install:
        - eclipse

  android_studio: Android Studio
    aur: true
    exec:
      install:
        - android-studio

  ninja_ide: Ninja Is Not Just Another IDE
    exec:
      install:
        - ninja-ide

  qt_creator: Qt Creator
    exec:
      install:
        - qtcreator

  kdevelop: KDevelop
    kde: true
    exec:
      install:
        - kdevelop


internet_browsers: Internet (Browsers)

  firefox: Firefox
    exec:
      - install:
        - firefox

  chromium: Chromium
    exec:
      - install:
        - chromium

  google_chrome: Google Chrome
    aur: true
    exec:
      - install:
        - google-chrome # TODO: Add Stable, Beta and Unstable

  vivaldi: Vivaldi
    aur: true
    exec:
      - install:
        - vivaldi # TODO: Same as Google Chrome


internet_im: Internet (IM)

  tdesktop32: Telegram Desktop (Official Client for 32 bits)
    exec:
      command: ["wget -c https://tdesktop.com/linux32", "tar xvf linux32", "sudo mv Telegram /opt/telegram", "rm -rf linux32", "./opt/telegram/Telegram"]

  tdesktop64: Telegram Desktop (Official Client for 64 bits)
    exec:
      command: ["wget -c https://tdesktop.com/linux", "tar xvf linux", "sudo mv Telegram /opt/telegram", "rm -rf linux", "./opt/telegram/Telegram"]


internet_voip: Internet (VOIP)

  mumble: Mumble
    exec:
      install:
        - mumble


internet_downloaders: Internet (Downloaders)

  qbittorrent: QBitTorrent
    exec:
      install:
        - qbittorrent

  uget: UGet
    exec:
      install:
        - uget

internet_uploaders: Internet (Uploaders)

  filezilla: FileZilla
    exec:
      install:
        - filezilla

games:

  steam: Valve's Steam
    exec:
      install:
        - steam

  vba: Visual Boy Advance (Game Boy/Color/Advance)
    exec:
      install:
        - vbam-gtk

  snes9x: SNES9x (Super Nintendo)
    exec:
      install:
        - snes9x-gtk
